apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
type: Opaque
data:
  DB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # Base64 encoded value of rootpassword
  DB_NAME: cGV0Y2xpbmlj # Base64 encoded value of petclinic
  DB_USER: cGV0Y2xpbmlj # Base64 encoded value of petclinic
  DB_PASSWORD: c2VjcmV0 # Base64 encoded value of secret
