apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  namespace: petclinic
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
